name: Deploy Docs

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/deploy_docs.yml'
      - 'docs/**'
      - 'include/**'

jobs:
  deploy_docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Doxygen
        run: |
          wget https://github.com/doxygen/doxygen/releases/download/Release_1_9_6/doxygen-1.9.6.linux.bin.tar.gz
          tar -xzf doxygen-1.9.6.linux.bin.tar.gz
          sudo mv doxygen-1.9.6/bin/doxygen /usr/local/bin

      - name: Install Poxy
        run: sudo pip install poxy==0.5.5

      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -S ${{ github.workspace }} -DBINARY_IO_BUILD_DOCS=ON -DBINARY_IO_BUILD_SRC=OFF -DBUILD_TESTING=OFF

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --target docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          force_orphan: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/build/docs/html/
